/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package edu.sjsu.assess.model;

public class AttemptElement {
	@org.codehaus.jackson.annotate.JsonProperty("questionnaireID")
	private java.lang.String questionnaireid;

 	public void setQuestionnaireid(java.lang.String questionnaireid) {
		this.questionnaireid = questionnaireid;
	}

	public java.lang.String getQuestionnaireid() {
		return questionnaireid;
	}

	@org.codehaus.jackson.annotate.JsonProperty("score")
	private java.lang.String score;

 	public void setScore(java.lang.String score) {
		this.score = score;
	}

	public java.lang.String getScore() {
		return score;
	}

	@org.codehaus.jackson.annotate.JsonProperty("attemptDate")
	private java.lang.String attemptdate;

 	public void setAttemptdate(java.lang.String attemptdate) {
		this.attemptdate = attemptdate;
	}

	public java.lang.String getAttemptdate() {
		return attemptdate;
	}

}